from config import *
from util import log, run_func_on_outputs
import pandas as pd
import numpy as np
from pathlib import Path

log("="*20 + " HISTORICAL AGGREGATES " + "="*20)


def process_hist_aggregates(input_df: pd.DataFrame, output_df: pd.DataFrame, dataset_type: str) -> tuple[pd.DataFrame, pd.DataFrame]:
    """
    Adds historical aggregate features without target leakage.

    Historical features are calculated as-of each row's reference date:
      - input rows: sales order date, with fallbacks to created/close/requested delivery date
      - output rows: invoice date

    Only invoices with invoice_date strictly before the row's reference date are
    used. This means the current row, same-day invoices, and all future invoices
    are excluded from the aggregates.

    Missing clearing dates are treated as real missing values, not censoring.
    Delay aggregates ignore missing clearing_date deltas naturally, and separate
    prior missing/known clearing-date rates are added.
    """

    ORDER_ID = "sales_order_id"

    # Keep only the historical groups that were useful enough to justify the
    # extra columns. The historical-feature ablation showed incoterm histories
    # were the weakest group, so they are no longer generated by default.
    GROUPING_SETS = {
        "client": ["client_number"],
        "terms_of_payment": ["terms_of_payment"],
        # Optional, but disabled by default to avoid a wide/noisy feature block:
        # "incoterms": ["incoterms_code"],
        # "client__terms_of_payment": ["client_number", "terms_of_payment"],
    }

    # Pruned historical metrics. The original version aggregated every date
    # delta, amount proxy, standard deviation, boolean sum, and incoterm group.
    # That made the feature block very wide and did not improve validation.
    # These allow-lists keep the interpretable/high-signal histories: prior
    # clearing delay, due-date lateness, invoice timing, payment-term length,
    # invoice/order size, and a clearing-date availability rate.
    HISTORICAL_DELTA_COLS = [
        "days__invoice_date__to__clearing_date",
        "days__payment_due_date__to__clearing_date",
        "days__so_date__to__invoice_date",
        "days__invoice_date__to__payment_due_date",
    ]

    HISTORICAL_AMOUNT_COLS = [
        "hist_invoice_amount",
        "hist_abs_invoice_amount",
        "hist_invoice_amount_company_signed",
        "hist_invoice_amount_company_abs",
        "hist_sales_order_amount",
        "hist_sales_order_expected_revenue",
    ]

    HISTORICAL_BOOL_COLS = [
        "hist_has_clearing_date",
    ]

    INPUT_DATE_COLS = [
        "so_date",
        "created_date",
        "req_deliv_date",
        "close_date",
        "bid_submission_date",
        "bid_validity",
    ]

    OUTPUT_DATE_COLS = [
        "invoice_date",
        "clearing_date",
        "payment_due_date",
    ]

    DATE_PAIRS = [
        ("so_date", "invoice_date"),
        ("so_date", "clearing_date"),
        ("created_date", "invoice_date"),
        ("created_date", "clearing_date"),
        ("invoice_date", "clearing_date"),
        ("invoice_date", "payment_due_date"),
        ("payment_due_date", "clearing_date"),
    ]

    # Business/accounting dates outside this range are almost certainly parsing
    # artefacts in this project. Keeping them as real timestamps can make pandas
    # overflow when subtracting two datetime arrays. They are therefore treated
    # as missing before any date-delta calculation or as-of merge.
    DATE_LOWER_BOUND = pd.Timestamp("1900-01-01")
    DATE_UPPER_BOUND = pd.Timestamp("2100-12-31")

    def ensure_datetime64ns(s: pd.Series) -> pd.Series:
        """Return a timezone-naive datetime64[ns] Series.

        pandas merge_asof is strict about matching datetime resolutions. CSV
        round-trips and arithmetic-generated dates can produce datetime64[us]
        in recent pandas versions, so normalise all internal merge keys to ns.
        """
        if not isinstance(s, pd.Series):
            s = pd.Series(s)

        out = pd.to_datetime(s, errors="coerce")
        out = pd.Series(out, index=s.index)

        # If a timezone-aware column ever appears, remove the timezone while
        # preserving the instant. Current project data is timezone-naive, but
        # this keeps the helper robust.
        try:
            if out.dt.tz is not None:
                out = out.dt.tz_convert(None)
        except AttributeError:
            pass

        # Guard against SAP/Salesforce placeholder dates or malformed values
        # that pandas may represent at a lower resolution. They can overflow
        # when converted/subtracted at ns resolution.
        out = out.mask(out.lt(DATE_LOWER_BOUND) | out.gt(DATE_UPPER_BOUND))

        return pd.Series(out.to_numpy(dtype="datetime64[ns]"), index=s.index)

    def parse_mixed_date(s: pd.Series) -> pd.Series:
        s = s.astype("string").str.strip()
        s = s.mask(s.isin(["", "nan", "NaN", "NaT", "None", "NULL"]))

        try:
            parsed = pd.to_datetime(s, errors="coerce", format="mixed", dayfirst=True)
        except TypeError:
            parsed = pd.to_datetime(s, errors="coerce", dayfirst=True)

        return ensure_datetime64ns(pd.Series(parsed, index=s.index))

    def rebuild_date(df: pd.DataFrame, base_col: str) -> pd.Series:
        day_col = f"{base_col}_day"
        month_col = f"{base_col}_month"
        year_col = f"{base_col}_year"

        out = pd.Series(pd.NaT, index=df.index, dtype="datetime64[ns]")

        if {day_col, month_col, year_col}.issubset(df.columns):
            parts = pd.DataFrame({
                "year": pd.to_numeric(df[year_col], errors="coerce"),
                "month": pd.to_numeric(df[month_col], errors="coerce"),
                "day": pd.to_numeric(df[day_col], errors="coerce"),
            })
            out = ensure_datetime64ns(pd.to_datetime(parts, errors="coerce"))

        if base_col in df.columns:
            out = out.fillna(parse_mixed_date(df[base_col]))

        return ensure_datetime64ns(out)

    def add_clean_dates(df: pd.DataFrame, date_cols: list[str]) -> pd.DataFrame:
        df = df.copy()

        for col in date_cols:
            has_raw_col = col in df.columns
            has_split_cols = {
                f"{col}_day",
                f"{col}_month",
                f"{col}_year",
            }.issubset(df.columns)
            if has_raw_col or has_split_cols:
                df[col] = rebuild_date(df, col)

        return df

    def safe_day_delta(start_dates: pd.Series, end_dates: pd.Series) -> pd.Series:
        """Return end-start in days without vectorized datetime overflow.

        pandas can raise ``OverflowError: Overflow in int64 addition`` when a
        datetime array contains a malformed/out-of-range value. This helper
        normalises both columns to the project date range, then subtracts only
        rows where both dates are valid. Invalid dates remain NaN.
        """
        start_clean = ensure_datetime64ns(start_dates)
        end_clean = ensure_datetime64ns(end_dates)

        out = pd.Series(np.nan, index=start_dates.index, dtype="float64")
        valid = start_clean.notna() & end_clean.notna()

        if valid.any():
            # Convert to ordinal day numbers before subtracting. This avoids
            # pandas' datetime-array overflow path and is enough for day-level
            # invoice/clearing features.
            start_days = start_clean.loc[valid].to_numpy(dtype="datetime64[D]").astype("int64")
            end_days = end_clean.loc[valid].to_numpy(dtype="datetime64[D]").astype("int64")
            out.loc[valid] = end_days - start_days

        return out

    def add_date_deltas(df: pd.DataFrame) -> pd.DataFrame:
        df = df.copy()

        for start, end in DATE_PAIRS:
            if start in df.columns and end in df.columns:
                df[start] = ensure_datetime64ns(df[start])
                df[end] = ensure_datetime64ns(df[end])
                df[f"days__{start}__to__{end}"] = safe_day_delta(df[start], df[end])

        return df

    def first_available_date(df: pd.DataFrame, cols: list[str]) -> pd.Series:
        out = pd.Series(pd.NaT, index=df.index, dtype="datetime64[ns]")

        for col in cols:
            if col in df.columns:
                out = out.fillna(ensure_datetime64ns(df[col]))

        return ensure_datetime64ns(out)

    def add_numeric_history_inputs(input_mod: pd.DataFrame, output_mod: pd.DataFrame) -> tuple[pd.DataFrame, pd.DataFrame]:
        input_mod = input_mod.copy()
        output_mod = output_mod.copy()

        if "amount" in input_mod.columns:
            input_mod["hist_sales_order_amount"] = pd.to_numeric(input_mod["amount"], errors="coerce")

        if "net_value" in input_mod.columns:
            input_mod["hist_sales_order_net_value"] = pd.to_numeric(input_mod["net_value"], errors="coerce")

        if "amount_converted" in input_mod.columns:
            input_mod["hist_sales_order_amount_converted"] = pd.to_numeric(input_mod["amount_converted"], errors="coerce")

        if "expected_revenue" in input_mod.columns:
            input_mod["hist_sales_order_expected_revenue"] = pd.to_numeric(input_mod["expected_revenue"], errors="coerce")

        if "invoice_amount_raw_signed" in output_mod.columns:
            output_mod["hist_invoice_amount"] = pd.to_numeric(output_mod["invoice_amount_raw_signed"], errors="coerce")
        elif "amount" in output_mod.columns:
            output_mod["hist_invoice_amount"] = pd.to_numeric(output_mod["amount"], errors="coerce")

        if "invoice_amount_abs" in output_mod.columns:
            output_mod["hist_abs_invoice_amount"] = pd.to_numeric(output_mod["invoice_amount_abs"], errors="coerce")
        elif "hist_invoice_amount" in output_mod.columns:
            output_mod["hist_abs_invoice_amount"] = output_mod["hist_invoice_amount"].abs()

        if "invoice_amount_company_signed" in output_mod.columns:
            output_mod["hist_invoice_amount_company_signed"] = pd.to_numeric(output_mod["invoice_amount_company_signed"], errors="coerce")

        if "invoice_amount_company_abs" in output_mod.columns:
            output_mod["hist_invoice_amount_company_abs"] = pd.to_numeric(output_mod["invoice_amount_company_abs"], errors="coerce")

        if "clearing_date" in output_mod.columns:
            output_mod["hist_has_clearing_date"] = output_mod["clearing_date"].notna()
            output_mod["hist_missing_clearing_date"] = output_mod["clearing_date"].isna()

        return input_mod, output_mod

    def build_group_key(df: pd.DataFrame, group_cols: list[str]) -> pd.Series:
        if not group_cols:
            return pd.Series("__all__", index=df.index)

        key_parts = []
        for col in group_cols:
            key_parts.append(df[col].astype("string").fillna("__MISSING__"))

        key_df = pd.concat(key_parts, axis=1)
        return key_df.agg("\x1f".join, axis=1)

    def add_cumulative_stats(
        daily: pd.DataFrame,
        group_col: str,
        value_col: str,
        prefix: str,
        include_std: bool = False,
    ) -> pd.DataFrame:
        """Add cumulative inclusive count/mean for one daily metric.

        Standard deviations were removed from the default historical block
        because they added many sparse columns with little validation benefit.
        """
        daily[f"{prefix}__count"] = daily.groupby(group_col)[f"{value_col}__count_daily"].cumsum()
        daily[f"{prefix}__sum"] = daily.groupby(group_col)[f"{value_col}__sum_daily"].cumsum()

        count = daily[f"{prefix}__count"].replace(0, np.nan)
        daily[f"{prefix}__mean"] = daily[f"{prefix}__sum"] / count

        if include_std:
            daily[f"{prefix}__sumsq"] = daily.groupby(group_col)[f"{value_col}__sumsq_daily"].cumsum()
            numerator = daily[f"{prefix}__sumsq"] - (daily[f"{prefix}__sum"] ** 2 / count)
            denominator = daily[f"{prefix}__count"] - 1
            variance = (numerator / denominator).where(denominator > 0)
            daily[f"{prefix}__std"] = np.sqrt(variance.clip(lower=0))
            daily = daily.drop(columns=[f"{prefix}__sumsq"])

        daily = daily.drop(columns=[f"{prefix}__sum"])
        return daily

    def build_time_aware_features(
        history_df: pd.DataFrame,
        target_df: pd.DataFrame,
        group_cols: list[str],
        grouping_name: str,
        reference_date_col: str,
    ) -> pd.DataFrame:
        if not set(group_cols).issubset(history_df.columns) or not set(group_cols).issubset(target_df.columns):
            return pd.DataFrame(index=target_df.index)

        if "invoice_date" not in history_df.columns or reference_date_col not in target_df.columns:
            return pd.DataFrame(index=target_df.index)

        delta_cols = [c for c in HISTORICAL_DELTA_COLS if c in history_df.columns]

        amount_cols = [c for c in HISTORICAL_AMOUNT_COLS if c in history_df.columns]

        bool_cols = [c for c in HISTORICAL_BOOL_COLS if c in history_df.columns]

        metric_cols = delta_cols + amount_cols
        feature_prefix = f"hist_{grouping_name}__"

        history = history_df[history_df["invoice_date"].notna()].copy()
        target = target_df[[*group_cols, reference_date_col]].copy()
        target["__target_index"] = target_df.index

        if history.empty:
            return pd.DataFrame(index=target_df.index)

        history["__group_key"] = build_group_key(history, group_cols)
        target["__group_key"] = build_group_key(target, group_cols)

        # Aggregate invoices by group/date first. This gives a compact table of
        # cumulative history states. The as-of join below uses allow_exact_matches=False,
        # so features are strictly based on invoice dates before the target date.
        daily = (
            history.groupby(["__group_key", "invoice_date"], dropna=False)
            .size()
            .rename(f"{feature_prefix}n_prior_rows")
            .reset_index()
        )
        daily[f"{feature_prefix}n_prior_rows"] = daily.groupby("__group_key")[f"{feature_prefix}n_prior_rows"].cumsum()

        if ORDER_ID in history.columns:
            first_order_dates = (
                history.dropna(subset=[ORDER_ID])
                .groupby(["__group_key", ORDER_ID], dropna=False)["invoice_date"]
                .min()
                .reset_index()
                .groupby(["__group_key", "invoice_date"], dropna=False)
                .size()
                .rename("__new_sales_orders_daily")
                .reset_index()
            )
            daily = daily.merge(first_order_dates, on=["__group_key", "invoice_date"], how="left")
            daily["__new_sales_orders_daily"] = daily["__new_sales_orders_daily"].fillna(0)
            daily[f"{feature_prefix}n_prior_sales_orders"] = daily.groupby("__group_key")["__new_sales_orders_daily"].cumsum()
            daily = daily.drop(columns=["__new_sales_orders_daily"])

        if "invoice_num" in history.columns:
            first_invoice_dates = (
                history.dropna(subset=["invoice_num"])
                .groupby(["__group_key", "invoice_num"], dropna=False)["invoice_date"]
                .min()
                .reset_index()
                .groupby(["__group_key", "invoice_date"], dropna=False)
                .size()
                .rename("__new_invoices_daily")
                .reset_index()
            )
            daily = daily.merge(first_invoice_dates, on=["__group_key", "invoice_date"], how="left")
            daily["__new_invoices_daily"] = daily["__new_invoices_daily"].fillna(0)
            daily[f"{feature_prefix}n_prior_invoices"] = daily.groupby("__group_key")["__new_invoices_daily"].cumsum()
            daily = daily.drop(columns=["__new_invoices_daily"])

        for col in metric_cols:
            numeric = pd.to_numeric(history[col], errors="coerce")
            metric_daily = pd.DataFrame({
                "__group_key": history["__group_key"],
                "invoice_date": history["invoice_date"],
                "__value": numeric,
                "__value_sumsq": numeric ** 2,
            })
            metric_daily = (
                metric_daily.groupby(["__group_key", "invoice_date"], dropna=False)
                .agg(
                    __metric_count_daily=("__value", "count"),
                    __metric_sum_daily=("__value", "sum"),
                    __metric_sumsq_daily=("__value_sumsq", "sum"),
                )
                .reset_index()
            )

            daily = daily.merge(metric_daily, on=["__group_key", "invoice_date"], how="left")
            daily[["__metric_count_daily", "__metric_sum_daily", "__metric_sumsq_daily"]] = daily[["__metric_count_daily", "__metric_sum_daily", "__metric_sumsq_daily"]].fillna(0)
            daily = daily.rename(columns={
                "__metric_count_daily": "__tmp__count_daily",
                "__metric_sum_daily": "__tmp__sum_daily",
                "__metric_sumsq_daily": "__tmp__sumsq_daily",
            })
            daily = add_cumulative_stats(daily, "__group_key", "__tmp", f"{feature_prefix}{col}")
            daily = daily.drop(columns=["__tmp__count_daily", "__tmp__sum_daily", "__tmp__sumsq_daily"])

        for col in bool_cols:
            bool_numeric = history[col].astype("boolean").astype("Float64")
            bool_daily = pd.DataFrame({
                "__group_key": history["__group_key"],
                "invoice_date": history["invoice_date"],
                "__value": bool_numeric,
            })
            bool_daily = (
                bool_daily.groupby(["__group_key", "invoice_date"], dropna=False)
                .agg(
                    __bool_count_daily=("__value", "count"),
                    __bool_sum_daily=("__value", "sum"),
                )
                .reset_index()
            )

            daily = daily.merge(bool_daily, on=["__group_key", "invoice_date"], how="left")
            daily[["__bool_count_daily", "__bool_sum_daily"]] = daily[["__bool_count_daily", "__bool_sum_daily"]].fillna(0)
            daily[f"{feature_prefix}{col}__count"] = daily.groupby("__group_key")["__bool_count_daily"].cumsum()
            bool_sum = daily.groupby("__group_key")["__bool_sum_daily"].cumsum()
            bool_count = daily[f"{feature_prefix}{col}__count"].replace(0, np.nan)
            daily[f"{feature_prefix}{col}__mean"] = bool_sum / bool_count
            daily = daily.drop(columns=["__bool_count_daily", "__bool_sum_daily"])

        daily["invoice_date"] = ensure_datetime64ns(daily["invoice_date"])
        target[reference_date_col] = ensure_datetime64ns(target[reference_date_col])

        daily = daily.sort_values(["__group_key", "invoice_date"]).reset_index(drop=True)
        target = target.sort_values(["__group_key", reference_date_col]).reset_index(drop=True)

        feature_tables = []
        feature_cols = [c for c in daily.columns if c not in ["__group_key", "invoice_date"]]

        for key, target_group in target.groupby("__group_key", dropna=False, sort=False):
            daily_group = daily[daily["__group_key"].eq(key)]

            if daily_group.empty:
                empty = target_group[["__target_index"]].copy()
                for col in feature_cols:
                    empty[col] = np.nan
                feature_tables.append(empty)
                continue

            left_group = target_group.copy()
            right_group = daily_group.copy()
            left_group[reference_date_col] = ensure_datetime64ns(left_group[reference_date_col])
            right_group["invoice_date"] = ensure_datetime64ns(right_group["invoice_date"])

            # merge_asof cannot match rows where the left key is NaT. Keep those
            # target rows and fill their historical features with NaN/0 later.
            left_with_date = left_group[left_group[reference_date_col].notna()].sort_values(reference_date_col)
            left_without_date = left_group[left_group[reference_date_col].isna()]

            if left_with_date.empty:
                merged = left_group[["__target_index"]].copy()
                for col in feature_cols:
                    merged[col] = np.nan
            else:
                merged = pd.merge_asof(
                    left_with_date,
                    right_group[right_group["invoice_date"].notna()].sort_values("invoice_date"),
                    left_on=reference_date_col,
                    right_on="invoice_date",
                    direction="backward",
                    allow_exact_matches=False,
                )
                merged = merged[["__target_index", *feature_cols]]

                if not left_without_date.empty:
                    missing_dates = left_without_date[["__target_index"]].copy()
                    for col in feature_cols:
                        missing_dates[col] = np.nan
                    merged = pd.concat([merged, missing_dates], ignore_index=True)

            feature_tables.append(merged[["__target_index", *feature_cols]])

        if not feature_tables:
            return pd.DataFrame(index=target_df.index)

        features = pd.concat(feature_tables, ignore_index=True).set_index("__target_index")
        features = features.reindex(target_df.index)

        count_like_cols = [
            c for c in features.columns
            if c.endswith("__count") or c.endswith("__sum") or c.endswith("n_prior_rows") or c.endswith("n_prior_sales_orders") or c.endswith("n_prior_invoices")
        ]
        features[count_like_cols] = features[count_like_cols].fillna(0)

        return features

    def append_time_aware_features(
        target_df: pd.DataFrame,
        history_df: pd.DataFrame,
        group_cols: list[str],
        grouping_name: str,
        reference_date_col: str,
    ) -> pd.DataFrame:
        features = build_time_aware_features(
            history_df=history_df,
            target_df=target_df,
            group_cols=group_cols,
            grouping_name=grouping_name,
            reference_date_col=reference_date_col,
        )

        if features.empty:
            return target_df

        target_df = target_df.drop(columns=[c for c in features.columns if c in target_df.columns], errors="ignore")
        return pd.concat([target_df, features], axis=1)

    input_mod = input_df.copy()
    output_mod = output_df.copy()
    # The output side is used internally as the invoice-history table, but this
    # step should not add historical columns to the returned output.csv. Keep a
    # pristine copy for the return value.
    output_return = output_df.copy()

    input_mod = add_clean_dates(input_mod, INPUT_DATE_COLS)
    output_mod = add_clean_dates(output_mod, OUTPUT_DATE_COLS)
    input_mod, output_mod = add_numeric_history_inputs(input_mod, output_mod)

    input_meta_cols = [
        ORDER_ID,
        "client_number",
        "account_name",
        "incoterms",
        "incoterms_code",
        "incoterms_group",
        "incoterms_country_or_region",
        "incoterms_is_standard_code",
        "incoterms_is_domestic_spain",
        "terms_of_payment",
        "terms_of_payment_days",
        "terms_of_payment_bucket",
        *INPUT_DATE_COLS,
        "hist_sales_order_amount",
        "hist_sales_order_net_value",
        "hist_sales_order_amount_converted",
        "hist_sales_order_expected_revenue",
    ]
    input_meta_cols = [c for c in input_meta_cols if c in input_mod.columns]

    input_meta = (
        input_mod[input_meta_cols]
        .drop_duplicates(subset=[ORDER_ID], keep="first")
        .copy()
    )

    output_mod["__hist_row_id"] = np.arange(len(output_mod))

    hist_base = output_mod.merge(
        input_meta,
        on=ORDER_ID,
        how="left",
        suffixes=("", "__from_input"),
    )

    # If output already had some metadata columns, fill missing values from input.
    for col in input_meta_cols:
        if col == ORDER_ID:
            continue

        from_input_col = f"{col}__from_input"
        if from_input_col in hist_base.columns:
            if col in hist_base.columns:
                hist_base[col] = hist_base[col].combine_first(hist_base[from_input_col])
                hist_base = hist_base.drop(columns=[from_input_col])
            else:
                hist_base = hist_base.rename(columns={from_input_col: col})

    hist_base = add_date_deltas(hist_base)
    hist_base = hist_base.sort_values("__hist_row_id").reset_index(drop=True)

    columns_to_copy_to_output = [
        "client_number",
        "account_name",
        "incoterms",
        "incoterms_code",
        "incoterms_group",
        "incoterms_country_or_region",
        "incoterms_is_standard_code",
        "incoterms_is_domestic_spain",
        "terms_of_payment",
        "terms_of_payment_days",
        "terms_of_payment_bucket",
        *INPUT_DATE_COLS,
        "hist_sales_order_amount",
        "hist_sales_order_net_value",
        "hist_sales_order_amount_converted",
        "hist_sales_order_expected_revenue",
    ]
    columns_to_copy_to_output.extend([c for c in hist_base.columns if c.startswith("days__")])

    for col in columns_to_copy_to_output:
        if col in hist_base.columns:
            output_mod[col] = hist_base[col].to_numpy()

    input_mod["__hist_reference_date"] = first_available_date(
        input_mod,
        ["so_date", "created_date", "close_date", "req_deliv_date", "bid_submission_date", "bid_validity"],
    )
    output_mod["__hist_reference_date"] = ensure_datetime64ns(output_mod["invoice_date"]) if "invoice_date" in output_mod.columns else pd.NaT

    # Use hist_base as the historical invoice table. Its rows are valid prior
    # observations only when invoice_date < target reference date.
    for grouping_name, group_cols in GROUPING_SETS.items():
        input_mod = append_time_aware_features(
            target_df=input_mod,
            history_df=hist_base,
            group_cols=group_cols,
            grouping_name=grouping_name,
            reference_date_col="__hist_reference_date",
        )

    input_mod = input_mod.drop(columns=["__hist_reference_date"], errors="ignore").reset_index(drop=True)
    output_return = output_return.reset_index(drop=True)

    return input_mod, output_return


# Prefer the newest upstream feature output. Fall back progressively so the
# script remains runnable even if it is executed alone during development.
if Path(INVOICE_SEMANTICS_DIR).exists():
    _HISTORY_INPUT_DIR = INVOICE_SEMANTICS_DIR
elif Path(INCOTERMS_DIR).exists():
    _HISTORY_INPUT_DIR = INCOTERMS_DIR
elif Path(TERMS_OF_PAYMENT_DIR).exists():
    _HISTORY_INPUT_DIR = TERMS_OF_PAYMENT_DIR
else:
    _HISTORY_INPUT_DIR = EXPAND_DATES_DIR

run_func_on_outputs(_HISTORY_INPUT_DIR, HISTORICAL_AGGREGATES_DIR, process_hist_aggregates)
