from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

LOG_DIR = BASE_DIR / "logs"

DATA_DIR = BASE_DIR / "data"

RAW_DIR = DATA_DIR / "raw"
SF_REPORT_RAW = RAW_DIR / "sf_report.csv"
SALES_ORDERES_RAW_DIR = RAW_DIR / "sales_orders"

PROCESSED_DIR = DATA_DIR / "processed"

PROCESSED_RENAMED_DIR = PROCESSED_DIR / "00_renamed"
PROCESSED_RENAMED_SALES_ORDERS_DIR = PROCESSED_RENAMED_DIR / "sales_orders"
PROCESSED_RENAMED_SF_REPORT = PROCESSED_RENAMED_DIR / "00_renamed_report.csv"

PROCESSED_NO_EMPTY_DIR = PROCESSED_DIR / "01_no_empty"
PROCESSED_NO_EMPTY_SALES_ORDERS_DIR = PROCESSED_NO_EMPTY_DIR / "sales_orders"
PROCESSED_NO_EMPTY_SF_REPORT = PROCESSED_NO_EMPTY_DIR / "01_no_empty_report.csv"

PROCESSED_DROP_COLS_LIST_DIR = PROCESSED_DIR / "02_drop_cols_list"
PROCESSED_DROP_COLS_LIST = PROCESSED_DROP_COLS_LIST_DIR / "02_drop_cols_list.csv"

PROCESSED_DROP_COLS_DIR = PROCESSED_DIR / "03_drop_cols"
PROCESSED_DROP_COLS_SALES_ORDERS_DIR = PROCESSED_DROP_COLS_DIR / "sales_orders"
PROCESSED_DROP_COLS_SF_REPORT = PROCESSED_DROP_COLS_DIR / "03_drop_cols_report.csv"

PROCESSED_PARSE_DATE_DIR = PROCESSED_DIR / "04_parse_dates"
PROCESSED_PARSE_DATE_SALES_ORDERS_DIR = PROCESSED_PARSE_DATE_DIR / "sales_orders"
PROCESSED_PARSE_DATE_SF_REPORT = PROCESSED_PARSE_DATE_DIR / "04_parse_date_report.csv"

PROCESSED_MERGE_INVOICES_DIR = PROCESSED_DIR / "05_merge_invoices"
PROCESSED_MERGE_INVOICES_SALES_ORDERS_DIR = PROCESSED_MERGE_INVOICES_DIR / "sales_orders"
PROCESSED_MERGE_INVOICES_SF_REPORT = PROCESSED_MERGE_INVOICES_DIR / "05_merge_invoices_report.csv"

PROCESSED_SEPARATE_X_Y_DIR = PROCESSED_DIR / "06_separate_X_y"
PROCESSED_SEPARATE_X_Y_SALES_ORDERS_DIR = PROCESSED_SEPARATE_X_Y_DIR / "sales_orders"

OUTPUT_DIR = DATA_DIR / "output"
