from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

LOG_DIR = BASE_DIR / "logs"

DATA_DIR = BASE_DIR / "data"

RAW_DIR = DATA_DIR / "raw"
SF_REPORT_RAW = RAW_DIR / "sf_report.csv"
SALES_ORDERES_RAW_DIR = RAW_DIR / "sales_orders"

PROCESSED_DIR = DATA_DIR / "processed"

PROCESSED_RENAMED_DIR = PROCESSED_DIR / "00_renamed"
PROCESSED_RENAMED_SALES_ORDERS_DIR = PROCESSED_RENAMED_DIR / "sales_orders"
PROCESSED_RENAMED_SF_REPORT = PROCESSED_RENAMED_DIR / "00_renamed_report.csv"

PROCESSED_NO_EMPTY_DIR = PROCESSED_DIR / "01_no_empty"
PROCESSED_NO_EMPTY_SALES_ORDERS_DIR = PROCESSED_NO_EMPTY_DIR / "sales_orders"
PROCESSED_NO_EMPTY_SF_REPORT = PROCESSED_NO_EMPTY_DIR / "01_no_empty_report.csv"

PROCESSED_DROP_COLS_LIST_DIR = PROCESSED_DIR / "02_drop_cols_list"
PROCESSED_DROP_COLS_LIST = PROCESSED_DROP_COLS_LIST_DIR / "02_drop_cols_list.csv"

PROCESSED_DROP_COLS_DIR = PROCESSED_DIR / "03_drop_cols"
PROCESSED_DROP_COLS_SALES_ORDERS_DIR = PROCESSED_DROP_COLS_DIR / "sales_orders"
PROCESSED_DROP_COLS_SF_REPORT = PROCESSED_DROP_COLS_DIR / "03_drop_cols_report.csv"

PROCESSED_PARSE_DATE_DIR = PROCESSED_DIR / "04_parse_dates"
PROCESSED_PARSE_DATE_SALES_ORDERS_DIR = PROCESSED_PARSE_DATE_DIR / "sales_orders"
PROCESSED_PARSE_DATE_SF_REPORT = PROCESSED_PARSE_DATE_DIR / "04_parse_date_report.csv"

PROCESSED_MERGE_INVOICES_DIR = PROCESSED_DIR / "05_merge_invoices"
PROCESSED_MERGE_INVOICES_SALES_ORDERS_DIR = PROCESSED_MERGE_INVOICES_DIR / "sales_orders"
PROCESSED_MERGE_INVOICES_SF_REPORT = PROCESSED_MERGE_INVOICES_DIR / "05_merge_invoices_report.csv"

PROCESSED_SEPARATE_X_Y_DIR = PROCESSED_DIR / "06_separate_X_y"
PROCESSED_SEPARATE_X_Y_SALES_ORDERS_DIR = PROCESSED_SEPARATE_X_Y_DIR / "sales_orders"

PROCESSED_CLEAN_COLUMNS_DIR = PROCESSED_DIR / "07_clean_columns"
PROCESSED_CLEAN_COLUMNS_SALES_ORDERS_DIR = PROCESSED_CLEAN_COLUMNS_DIR / "sales_orders"

DATA_CLEANING_OUTPUT_COMPLETE_FOLDER = "complete_clearings"
DATA_CLEANING_OUTPUT_CLEARING_FOLDER = "no_empty_clearings"
DATA_CLEANING_OUTPUT_FULL_FOLDER = "full_dataset"

DATA_CLEANING_OUTPUT_DIR = DATA_DIR / "data_cleaning_output"
DATA_CLEANING_OUTPUT_COMPLETE_DIR = DATA_CLEANING_OUTPUT_DIR / DATA_CLEANING_OUTPUT_COMPLETE_FOLDER
DATA_CLEANING_OUTPUT_CLEARING_DIR = DATA_CLEANING_OUTPUT_DIR / DATA_CLEANING_OUTPUT_CLEARING_FOLDER
DATA_CLEANING_OUTPUT_FULL_DIR = DATA_CLEANING_OUTPUT_DIR / DATA_CLEANING_OUTPUT_FULL_FOLDER

FEATURE_ENGINEERING_DIR = DATA_DIR / "feature_engineering"

EXPAND_DATES_DIR = FEATURE_ENGINEERING_DIR / "01_expanded_dates"
TERMS_OF_PAYMENT_DIR = FEATURE_ENGINEERING_DIR / "02_terms_of_payment"
INCOTERMS_DIR = FEATURE_ENGINEERING_DIR / "03_normalized_incoterms"
INVOICE_SEMANTICS_DIR = FEATURE_ENGINEERING_DIR / "04_invoice_semantics"
HISTORICAL_AGGREGATES_DIR = FEATURE_ENGINEERING_DIR / "05_historical_aggregates"

# Stable feature-engineering output snapshot used by downstream models.
FEATURE_ENGINEERING_OUTPUT_DIR = DATA_DIR / "feature_engineering_output"
FEATURE_ENGINEERING_OUTPUT_COMPLETE_DIR = FEATURE_ENGINEERING_OUTPUT_DIR / DATA_CLEANING_OUTPUT_COMPLETE_FOLDER
FEATURE_ENGINEERING_OUTPUT_CLEARING_DIR = FEATURE_ENGINEERING_OUTPUT_DIR / DATA_CLEANING_OUTPUT_CLEARING_FOLDER
FEATURE_ENGINEERING_OUTPUT_FULL_DIR = FEATURE_ENGINEERING_OUTPUT_DIR / DATA_CLEANING_OUTPUT_FULL_FOLDER

MODEL_OUTPUTS_DIR = DATA_DIR / "model_outputs"
CLEARING_DATE_FORECASTER_DIR = MODEL_OUTPUTS_DIR / "clearing_date_forecaster"

INVOICE_FORECASTER_DIR = MODEL_OUTPUTS_DIR / "invoice_forecaster"
